### ISSUE TITLE
Specify serialization workflow of `plonky2` proofs

### ISSUE THREAD

**Issue by mertwole** [succinctlabs/gnark-plonky2-verifier#46]
It'd be nice to specify in `README.md` the way you serialize `plonky2` proofs or even short example of `plonky2` circuit that generates test data. For now I see that `plonky2` serialization([commit](https://github.com/succinctlabs/plonky2/commit/79c6de140dd76c6d3ae8769d453a9f723adf0e6e)) yields `Poseidon` digest in the form:
```
"elements": [
    14531856720230017218,
    13425020541298287362,
    4998835710682442515,
    11706161533356057222
]
```
but in examples you have one `BigInt` for that. I've tried to override implementation of `Serailize` for `HashOut` in `plonky2` but then it fails to verify dummy proof.

**Comment by akorchyn** [comment]
so is there any work around?

**Comment by akorchyn** [comment]
Seems to be I have resolved it. You need to create a recursive proof with PoseidonBN128GoldilocksConfig

**Comment by mertwole** [comment]
Yes, I've forgot about this issue but what you need to do is to take [succinctx' wrapper implementation](https://github.com/succinctlabs/succinctx/tree/main/plonky2x/core/src/backend/wrapper)

**Comment by pixelcircuits** [comment]
I cloned the [wrapper implementation](https://github.com/succinctlabs/succinctx/tree/main/plonky2x/core/src/backend/wrapper) (minus the hash and recursive circuit) so that it just straight wraps my circuit to a PoseidonBN128GoldilocksConfig circuit. The serialization is correct now and the proof verifies just fine in rust with plonky2, but running to get a groth16 wrapped proof is still resulting in:
```
ERR error="constraint #1150973 is not satisfied: 1 ⋅ 5997089901330489012 != 14708909024249022512" nbConstraints=5323282
```

Does the PoseidonBN128GoldilocksConfig circuit have to be of a specific degree or something?

EDIT:
I resolved the issue after setting the plonky2 version explicitly to v0.2.3
